load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "fake",
    srcs = [
        "clientset_generated.go",
        "doc.go",
        "register.go",
    ],
    importpath = "github.com/alexgmm/learn-bazel/go/kube-cli/pkg/client/versioned/fake",
    visibility = ["//visibility:public"],
    deps = [
        "//go/kube-cli/pkg/api/statectl/v1alpha1",
        "//go/kube-cli/pkg/client/versioned",
        "//go/kube-cli/pkg/client/versioned/typed/statectl/v1alpha1",
        "//go/kube-cli/pkg/client/versioned/typed/statectl/v1alpha1/fake",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/runtime/schema",
        "@io_k8s_apimachinery//pkg/runtime/serializer",
        "@io_k8s_apimachinery//pkg/util/runtime",
        "@io_k8s_apimachinery//pkg/watch",
        "@io_k8s_client_go//discovery",
        "@io_k8s_client_go//discovery/fake",
        "@io_k8s_client_go//testing",
    ],
)
