load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "v1alpha1",
    srcs = [
        "doc.go",
        "groupversion_info.go",
        "register.go",
        "types.go",
    ],
    importpath = "github.com/alexgmm/learn-bazel/go/kube-cli/pkg/api/statectl/v1alpha1",
    visibility = ["//visibility:public"],
    deps = [
        "//go/kube-cli/pkg/api/statectl",
        "@io_k8s_apimachinery//pkg/apis/meta/v1:meta",
        "@io_k8s_apimachinery//pkg/runtime",
        "@io_k8s_apimachinery//pkg/runtime/schema",
    ],
)
